// Mocks generated by Mockito 5.4.6 from annotations
// in streaming_app/test/features/movies/domain/usecase/get_movie_detail_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:streaming_app/core/network/core_base_reponse.dart' as _i2;
import 'package:streaming_app/features/home/domain/entity/home_category_entity.dart'
    as _i10;
import 'package:streaming_app/features/home/presentation/cubit/home_config_cubit.dart'
    as _i9;
import 'package:streaming_app/features/home/presentation/cubit/home_config_state.dart'
    as _i3;
import 'package:streaming_app/features/movies/domain/entity/movie_detail_entity.dart'
    as _i8;
import 'package:streaming_app/features/movies/domain/entity/movies_list_entity.dart'
    as _i6;
import 'package:streaming_app/features/movies/domain/entity/movies_list_filter.dart'
    as _i7;
import 'package:streaming_app/features/movies/domain/repository/movies_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCoreBaseResponse_0<Data> extends _i1.SmartFake
    implements _i2.CoreBaseResponse<Data> {
  _FakeCoreBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeConfigState_1 extends _i1.SmartFake
    implements _i3.HomeConfigState {
  _FakeHomeConfigState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i4.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>> getMoviesNowPlaying(
          _i7.MoviesListFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoviesNowPlaying,
          [filter],
        ),
        returnValue:
            _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>>.value(
                _FakeCoreBaseResponse_0<_i6.MoviesListEntity>(
          this,
          Invocation.method(
            #getMoviesNowPlaying,
            [filter],
          ),
        )),
      ) as _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>>);

  @override
  _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>> getMoviesPopular(
          _i7.MoviesListFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoviesPopular,
          [filter],
        ),
        returnValue:
            _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>>.value(
                _FakeCoreBaseResponse_0<_i6.MoviesListEntity>(
          this,
          Invocation.method(
            #getMoviesPopular,
            [filter],
          ),
        )),
      ) as _i5.Future<_i2.CoreBaseResponse<_i6.MoviesListEntity>>);

  @override
  _i5.Future<_i2.CoreBaseResponse<_i8.MovieDetailEntity>> getMovieDetails(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [movieId],
        ),
        returnValue:
            _i5.Future<_i2.CoreBaseResponse<_i8.MovieDetailEntity>>.value(
                _FakeCoreBaseResponse_0<_i8.MovieDetailEntity>(
          this,
          Invocation.method(
            #getMovieDetails,
            [movieId],
          ),
        )),
      ) as _i5.Future<_i2.CoreBaseResponse<_i8.MovieDetailEntity>>);
}

/// A class which mocks [HomeConfigCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeConfigCubit extends _i1.Mock implements _i9.HomeConfigCubit {
  MockHomeConfigCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.HomeCategoryEntity> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i10.HomeCategoryEntity>[],
      ) as List<_i10.HomeCategoryEntity>);

  @override
  _i3.HomeConfigState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomeConfigState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.HomeConfigState);

  @override
  _i5.Stream<_i3.HomeConfigState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.HomeConfigState>.empty(),
      ) as _i5.Stream<_i3.HomeConfigState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.HomeConfigState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i3.HomeConfigState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
