// Mocks generated by Mockito 5.4.6 from annotations
// in streaming_app/test/features/movies/data/repository/movies_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:streaming_app/features/movies/data/datasource/movies_remote_datasource.dart'
    as _i4;
import 'package:streaming_app/features/movies/data/model/movie_detail_response_model.dart'
    as _i3;
import 'package:streaming_app/features/movies/data/model/movies_list_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMoviesListModel_0 extends _i1.SmartFake
    implements _i2.MoviesListModel {
  _FakeMoviesListModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponseModel_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponseModel {
  _FakeMovieDetailResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRemoteDatasource extends _i1.Mock
    implements _i4.MoviesRemoteDatasource {
  MockMoviesRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.MoviesListModel> listMoviesNowPlaying(
    int? page,
    String? language,
    String? region,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMoviesNowPlaying,
          [
            page,
            language,
            region,
          ],
        ),
        returnValue:
            _i5.Future<_i2.MoviesListModel>.value(_FakeMoviesListModel_0(
          this,
          Invocation.method(
            #listMoviesNowPlaying,
            [
              page,
              language,
              region,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MoviesListModel>);

  @override
  _i5.Future<_i2.MoviesListModel> listPopularMovies(
    int? page,
    String? language,
    String? region,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listPopularMovies,
          [
            page,
            language,
            region,
          ],
        ),
        returnValue:
            _i5.Future<_i2.MoviesListModel>.value(_FakeMoviesListModel_0(
          this,
          Invocation.method(
            #listPopularMovies,
            [
              page,
              language,
              region,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MoviesListModel>);

  @override
  _i5.Future<_i3.MovieDetailResponseModel> getMovieDetails(
    int? movieId,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [
            movieId,
            language,
          ],
        ),
        returnValue: _i5.Future<_i3.MovieDetailResponseModel>.value(
            _FakeMovieDetailResponseModel_1(
          this,
          Invocation.method(
            #getMovieDetails,
            [
              movieId,
              language,
            ],
          ),
        )),
      ) as _i5.Future<_i3.MovieDetailResponseModel>);
}
